# camera vendor, 0:sensing, 1:lijing
vendor: "sensing"
sensor: "imx390"
# camsrc is the origin size of camera, can only be 3840x2160(for imx424b) or 1920x1080(for imx390)
camsrcwidth: 1920
camsrcheight: 1080
# in general the distor img size should be the same with camera img origin size, otherwise there will be a high latency,
# this parameter is kept only for 4k camera
distorWidth: 1920
distorHeight: 1080
# undistor size can only be 960x540 or 1920x1080
undistor: false
undistorWidth: 960
undistorHeight: 540
outPutWidth: 960
outPutHeight: 540
fov: 120

# camera params path
cameraparams: "../cfg/cameras.yaml"

# parameters for renderer
renderWidth: 1920
renderHeight: 1080
renderX: 0
renderY: 0
renderBufWidth: 1920
renderBufHeight: 1080
# 0 for egl, 1 for opencv
renderMode: 0

num_images: 4

USED_CAMERA_NUM: 1
# netpath: "/home/nvidia/ssd/model/yolo4_berkeley_fp16_bs1.rt"
# netpath: "/home/nvidia/ssd/model/yolo4_berkeley_fp16_bs1_new.rt"
netpath: "/home/nvidia/ssd/model/yolo4_berkeley_fp16_bs4.rt"
# netpath: "/home/nvidia/ssd/model/yolo4tiny_fp16.rt"
# netpath: "/home/nvidia/ssd/model/yolo4_kitti_fp16_bs4.rt"
camcfgpath: "../cfg/390camcfg/"
# camcfgpath: "/home/nvidia/ssd/code/Img-Stitching/cfg/390camcfg/"
canname: "can0" 
camDispIdx: "1"

loglvl: "debug"

# parameters for stitcher
stitcherMatchConf: 0.3
stitcherAdjusterConf: 0.7
stitcherBlenderStrength: 0
stitcherCameraExThres: 30
stitcherCameraInThres: 100

# init mode, 1:initall, 2:use default, init seam, 3:read cfg, init seam
initMode: 1

# parameters for detector
batchSize: 1