# camera vendor, 0:sensing, 1:lijing
vendor: lijing
sensor: imx390
sttype: 4cam-black
# camsrc is the origin size of camera, can only be 3840x2160(for imx424b) or 1920x1080(for imx390)
camsrcwidth: 1920
camsrcheight: 1080
# in general the distor img size should be the same with camera img origin size, otherwise there will be a high latency,
# this parameter is kept only for 4k camera
distorWidth: 1920
distorHeight: 1080
# undistor size can only be 960x540 or 1920x1080
undistor: true
undistorWidth: 960
undistorHeight: 540
outPutWidth: 960 # 800 # 720 #640
outPutHeight: 540 # 450 # 405 #360
fov: 120

imgcut: 40

# camera params path
cameraparams: "/home/nx/code/release/cameras.yaml"

# parameters for renderer
renderWidth: 1280
renderHeight: 720
renderX: 0
renderY: 0
renderBufWidth: 1280
renderBufHeight: 720
# 0 for egl, 1 for opencv(deprecated), 2 for no display
renderMode: 2

num_images: 2

USED_CAMERA_NUM: 4
netpath: "/home/nx/code/release/xjtu_detNN.rt"
camcfgpath: "../cfg/390camcfg/"
# camcfgpath: "/home/nvidia/ssd/code/Img-Stitching/cfg/390camcfg/"
canname: "can0" 
camDispIdx: "a"

loglvl: "info"

# parameters for stitcher
stitcherMatchConf: 0.3
stitcherAdjusterConf: 0.7
stitcherBlenderStrength: 1
stitcherCameraExThres: 30
stitcherCameraInThres: 500

# init mode, 1:initall, 2:use default, init seam, 3:read cfg, init seam
initMode: 2

# parameters for detector
batchSize: 1

# websocket dst url
# websocketurl: "ws://192.168.168.171:9002" # "ws://localhost:9002"
websocketurl: "ws://localhost:9002"
websocketOn: true
websocketPort: 9002
